name: Java CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'

      # Step 3: Compile the Java source code (如果你有多个文件需要编译，使用 javac 命令编译所有 .java 文件)
      - name: Compile Java source files
        run: |
          mkdir -p target/classes
          javac -d target/classes src/*.java  # 假设 Java 源代码在 src/ 文件夹中，编译所有 .java 文件

      # Step 4: Run the Java application
      - name: Run Java class
        run: |
          java -cp target/classes MAIN  # 运行你的 Main 类
