name: Java CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK 8 with distribution (AdoptOpenJDK)
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'adoptopenjdk'  # 设置 JDK 发行版为 AdoptOpenJDK

    # Step 3: Compile the Java source code
    - name: Compile Java source files
      run: |
        mkdir -p target/classes
        javac -d target/classes src/*.java  # 编译 src 目录中的所有 .java 文件

    # Step 4: Run the Java application
    - name: Run Java class
      run: |
        java -cp target/classes MAIN  # 运行 Main 类
